---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: newdeployment
spec:
  replicas: 2
  
  selector:
    matchLabels:
      app: sample
  template:
    metadata:
      name: newpod
      labels:
        app: sample
    spec:
     containers:
     - name: newcontainer
       image: allureddy/allu
       ports:
       - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: newservice
spec:
  selector:
     app: sample
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30001

---
